### ISSUE TITLE
Making the widgets 'live'

### ISSUE THREAD

**Issue by surbhitrao** [DagW/FragmentHomescreen#2]
Although the widgets can be added but they are not live in true sense.For example take a music app for example if you added its widget in this app and now make play/pause it from the background that change wont be reflected in this app.For that just comment these following lines.

	@Override
	public void onStop () {
		super.onStop();
		if(appWidgetHost != null)
			getAppWidgetHost().stopListening();
	}

in the MainActivity class.

**Comment by DagW** [comment]
True. The issue is not that it stops listening, I think its more that it might not start up again?
Ill see how I've solved this.

**Comment by surbhitrao** [comment]
It worked fine for me.
