### ISSUE TITLE
Some widgets are too 'short' in height

### ISSUE THREAD

**Issue by surbhitrao** [DagW/FragmentHomescreen#3]
Although we must be able to resize them dynamically.For now you can do it programatically.
Make this change in the WidgetContainer class.

LinearLayout.LayoutParams params = new LinearLayout.LayoutParams((inInfo.Width), (inInfo.Height)+700);
  
Make sure to define 
public int Height = -1;
public int Width = -1;
in ItemInfo.java class.

**Comment by DagW** [comment]
Yup.
Your change would add 700 in height to all added widgets?

Also if you obtain a reference to the view, you can set 

```
FrameLayout.LayoutParams params = new LayoutParams( width * cellSizeX, (height * cellSizeY) );
params.setMargins( (x) * cellSizeX, (y) * (cellSizeY + Utilities.dpToPx( widgetmargin )), 0, 0 );
view.setLayoutParams(params);
```
Then you dont have to do it at creation-time.

**Comment by surbhitrao** [comment]
Great :)
